language: c

cache:
  - apt

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get -q install valgrind
  - sudo apt-get -q install unixodbc unixodbc-dev libsqliteodbc

before_script:
  - source etc/krproject.env
  - echo "[$DBNAME]\nDescription = SQLite database\n Driver = SQLite3\n Database = `pwd`/krproject.sqlite3\n Timeout = 2000\n" >> ~/.odbc.ini
  - sqlite3 `pwd`/krproject.sqlite3 < doc/krproject_sqlite3.sql
  - mkdir -p _install

script:
  - git clean -xdf
  - ./configure && make distcheck VERBOSE=1 && make clean
  - ./configure --prefix=`pwd`/_install && make VERBOSE=1 && make install

